import Head from 'next/head'
import { Inter } from '@next/font/google'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiTwotoneMail} from "react-icons/ai";
import { GoMarkGithub } from "react-icons/go";
import Image from 'next/image';
import deved from "../public/dev-ed-wave.png";
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web1.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

import { useState } from 'react';



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <>
    <div className= {darkMode ? "dark" : ""}>
      <Head>
        <title>First Por</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className="min-h-screen">

          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl 
                          font-burtons
                          dark:text-white'>
                            WORKERsome
            </h1>

            <ul className='flex items-center'>

              {/* THEME */}
              <li>
                <BsFillMoonStarsFill onClick={() =>setDarkMode(!darkMode) } 
                  className='cursor-pointer text-2xl'/>
              </li>

              {/* RESUME BUTTON */}
              <li>
                <a 
                  className=' bg-gradient-to-r
                             from-cyan-500
                             to-teal-500
                             text-white 
                              px-4 
                              py-2 
                              rounded-md 
                              ml-8' 
                    href='#'>Resume
                  </a>
              </li>
            </ul>

          </nav>

          {/* PARAGRAPH */}
          <div className='text-center p-10 py-10'>
            <h2 className=' text-5xl 
                            py-2
                           text-teal-600 
                            font-medium
                            md: text-6xl'>
              Nantakarn Chinsakchai
            </h2>
            <h3 className=' text-2xl 
                            py-2
                            md:text-3xl
                            dark:text-white'>
              Font-End Developer.
            </h3>
            <p className=' text-md 
                          py-5 
                          leading-8
                         text-gray-800
                          md:text-xl
                          max-w-lg
                          mx-auto
                          dark:text-white'>
              A front-end developer creates websites and applications using web languages such as HTML, CSS, and JavaScript that allow users to access and interact with the site or app. When you visit a website, the design elements you see were created by a front-end developer.
            </p>
          </div>


          {/* ICON START */}
          <div className='text-5xl 
                          flex 
                          justify-center 
                          gap-16 
                          py-3
                         text-gray-600'>
            <a href='https://github.com/Nun28th347'><GoMarkGithub/></a>
            <AiFillLinkedin/>
            <a href="mailto:nunza489@gmail.com"><AiTwotoneMail/></a>
          </div>

          <div className=' relative 
                          mx-auto 
                          bg-gradient-to-b
                         from-teal-500 
                         rounded-full 
                         w-80 
                         h-80 
                         mt-20 
                         overflow-hidden
                         md:h-96
                         md:w-96'>
            <Image src={deved} layout='fill' objectFit='cover' />
          </div>

        </section>

        {/* ICON END*/}

        {/* Services I offer START */}
        <section>
          <div>
            <h3 className=' text-3xl 
                            py-1
                            dark:text-white'>
                              Services I offer
            </h3>
            <p className=' text-md 
                          py-2 
                          leading-8
                         text-gray-800
                         dark:text-white'>
              Freelance front-end development involves creating and implementing website/app visual and interactive elements using HTML, CSS, JavaScript, and design tools. <span className=' text-teal-500'> agencies</span> Ensures seamless <span className='text-teal-500'> user </span> experience and works with clients, designers and back-end developers to bring project vision.
            </p>
            <p className=' text-md
                           py-2 
                           leading-8 
                           text-gray-800
                           dark:text-white'>
              They work closely with back-end developers, designers, and clients to bring the project vision to life and ensure that it meets the client's requirements and expectations.
            </p>
          </div>

          <div className='lg:flex gap-10'>
            {/* <div className=' text-center items-center justify-center shadow-lg p-10 rounded-xl my-10'> */}
            <div class=" flex 
                        flex-col 
                        items-center  
                        shadow-lg 
                        p-10 
                        rounded-xl 
                        my-10
                        dark:bg-white">

              <Image class="w-32 
                            h-32 
                            rounded-full " 
                            src= {design} width={100} height={100} />
              <h3 className=' text-lg font-medium pt-8 pb-2'>Beautiful Designers</h3>
              <p className=' py-2'>
                Creating elegant design suited for your needs delivers personalized, unique solutions that meet specific requirements and reflect client's style and vision. Focuses on both aesthetic appeal and functionality for a seamless experience. Exceeds expectations with sophisticated and customized designs.
              </p>
              <h4 className=' py-4 text-teal-600'>Design tools I use</h4>
              <p className=' text-gray-800 py-1'>Photoshop</p>
              <p className=' text-gray-800 py-1'>HTML CSS JavaScript</p>
              <p className=' text-gray-800 py-1'>React ,Node js</p>
            </div>


            <div class=" flex 
                        flex-col 
                        items-center  
                        shadow-lg 
                        p-10 
                        rounded-xl 
                        my-10
                        dark:bg-white">
              <Image class="w-32 h-32 rounded-full " src= {code} width={100} height={100} />
              <h3 className=' text-lg font-medium pt-8 pb-2'>Beautiful Designers</h3>
              <p className=' py-2'>
                Creating elegant design suited for your needs delivers personalized, unique solutions that meet specific requirements and reflect client's style and vision. Focuses on both aesthetic appeal and functionality for a seamless experience. Exceeds expectations with sophisticated and customized designs.
              </p>
              <h4 className=' py-4 text-teal-600'>Design tools I use</h4>
              <p className=' text-gray-800 py-1'>Photoshop</p>
              <p className=' text-gray-800 py-1'>HTML CSS JavaScript</p>
              <p className=' text-gray-800 py-1'>React ,Node js</p>
            </div>


            <div class=" flex 
                        flex-col 
                        items-center  
                        shadow-lg p-10 
                        rounded-xl 
                        my-10
                        dark:bg-white">
              <Image class="w-32 h-32 rounded-full " src= {consulting} width={100} height={100} />
              <h3 className=' text-lg font-medium pt-8 pb-2'>Beautiful Designers</h3>
              <p className=' py-2'>
                Creating elegant design suited for your needs delivers personalized, unique solutions that meet specific requirements and reflect client's style and vision. Focuses on both aesthetic appeal and functionality for a seamless experience. Exceeds expectations with sophisticated and customized designs.
              </p>
              <h4 className=' py-4 text-teal-600'>Design tools I use</h4>
              <p className=' text-gray-800 py-1'>Photoshop</p>
              <p className=' text-gray-800 py-1'>HTML CSS JavaScript</p>
              <p className=' text-gray-800 py-1'>React ,Node js</p>
            </div>

          </div>

        </section>

        {/* Services I offer END */}



        {/* Portofolio START */}

        <section>
          <div>
            <h3 className=' text-3xl 
                            py-1
                            dark:text-white'>
                              Portofolio
            </h3>
            <p className=' text-md 
                          py-2 
                          leading-8 
                          text-gray-800
                          dark:text-white'>
              Freelance front-end development involves creating and implementing website/app visual and interactive elements using HTML, CSS, JavaScript, and design tools. <span className=' text-teal-500'> agencies</span> Ensures seamless <span className='text-teal-500'> user </span> experience and works with clients, designers and back-end developers to bring project vision.
            </p>
            <p className=' text-md 
                          py-2 
                          leading-8 
                          text-gray-800
                          dark:text-white'>
              They work closely with back-end developers, designers, and clients to bring the project vision to life and ensure that it meets the client's requirements and expectations.
            </p> 
          </div>

        {/* Portofolio END */}


      {/* WORK IMG */}
          <div className=' flex
                           flex-col
                           gap-10
                           lg:flex-row
                           lg:flex-wrap'>
            <div className=' basis-1/3
                              flex-1'>
              <Image src={web1} className=" rounded-lg 
                                            object-cover" 
                                            width={"100%"} 
                                            height={"100%"} 
                                            layout="responsive" />
            </div>
              
            <div className=' basis-1/3
                              flex-1'>
              <Image src={web2} className=" rounded-lg 
                                            object-cover" 
                                            width={"100%"} 
                                            height={"100%"} 
                                            layout="responsive" />
            </div>

            <div className=' basis-1/3
                              flex-1'>
              <Image src={web3} className=" rounded-lg 
                                            object-cover" 
                                            width={"100%"} 
                                            height={"100%"} 
                                            layout="responsive" /> 
            </div>

            <div className=' basis-1/3
                              flex-1'>
              <Image src={web4} className=" rounded-lg 
                                            object-cover" 
                                            width={"100%"} 
                                            height={"100%"} 
                                            layout="responsive" /> 
            </div>

            <div className=' basis-1/3
                              flex-1'>
              <Image src={web5} className=" rounded-lg 
                                            object-cover" 
                                            width={"100%"} 
                                            height={"100%"} 
                                            layout="responsive" />
            </div>

            <div className=' basis-1/3
                              flex-1'>
              <Image src={web6} className=" rounded-lg 
                                            object-cover" 
                                            width={"100%"} 
                                            height={"100%"} 
                                            layout="responsive" />
            </div>

            {/* 50.00 */}
          </div>
        </section>

      </main>
    </div>
    </>
  )
}
